package gui_designer_sandbox.forms;

import com.intellij.uiDesigner.core.Spacer;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

public class VipsPlaygroundControls {
    private JPanel controlPanel;
    private JSpinner spinner1;
    private JSpinner spinner2;
    private JLabel ySpinnerLabel;
    private JSpinner spinner3;
    private JSpinner spinner4;
    private JButton openFileButton;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        controlPanel = new JPanel();
        controlPanel.setLayout(new FormLayout("fill:d:grow,left:5dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:d:grow", "center:max(d;10px):noGrow,center:18px:noGrow,top:5dlu:noGrow,center:27px:noGrow,top:8dlu:noGrow,center:14px:noGrow,top:5dlu:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        final JLabel label1 = new JLabel();
        label1.setText("X:");
        CellConstraints cc = new CellConstraints();
        controlPanel.add(label1, new CellConstraints(1, 9, 1, 1, CellConstraints.DEFAULT, CellConstraints.DEFAULT, new Insets(0, 5, 0, 0)));
        spinner1 = new JSpinner();
        controlPanel.add(spinner1, cc.xy(3, 9, CellConstraints.FILL, CellConstraints.DEFAULT));
        spinner2 = new JSpinner();
        controlPanel.add(spinner2, cc.xy(7, 9, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label2 = new JLabel();
        label2.setText("Overlay image parameters");
        controlPanel.add(label2, cc.xyw(1, 2, 7, CellConstraints.DEFAULT, CellConstraints.FILL));
        ySpinnerLabel = new JLabel();
        ySpinnerLabel.setText("Y:");
        controlPanel.add(ySpinnerLabel, cc.xy(5, 9));
        final JLabel label3 = new JLabel();
        label3.setText("Width:");
        controlPanel.add(label3, new CellConstraints(1, 11, 1, 1, CellConstraints.DEFAULT, CellConstraints.DEFAULT, new Insets(0, 5, 0, 0)));
        spinner3 = new JSpinner();
        controlPanel.add(spinner3, cc.xy(3, 11, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label4 = new JLabel();
        label4.setText("Height:");
        controlPanel.add(label4, cc.xy(5, 11));
        spinner4 = new JSpinner();
        controlPanel.add(spinner4, cc.xy(7, 11, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JSeparator separator1 = new JSeparator();
        separator1.setForeground(new Color(-7566196));
        controlPanel.add(separator1, cc.xywh(1, 13, 7, 5, CellConstraints.FILL, CellConstraints.TOP));
        final JLabel label5 = new JLabel();
        label5.setText("Text inset parameters");
        controlPanel.add(label5, cc.xyw(1, 19, 7));
        final JLabel label6 = new JLabel();
        label6.setText("Rectangle bounds");
        controlPanel.add(label6, cc.xy(1, 6));
        openFileButton = new JButton();
        openFileButton.setText("Open file...");
        controlPanel.add(openFileButton, cc.xy(1, 4));
        final Spacer spacer1 = new Spacer();
        controlPanel.add(spacer1, cc.xy(1, 1, CellConstraints.DEFAULT, CellConstraints.FILL));
        final JSeparator separator2 = new JSeparator();
        separator2.setForeground(new Color(-7566196));
        controlPanel.add(separator2, cc.xyw(1, 5, 7, CellConstraints.FILL, CellConstraints.CENTER));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return controlPanel;
    }

}
