package gui_designer_sandbox.forms;

import com.intellij.uiDesigner.core.Spacer;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

public class VipsPlaygroundControls {
    private JPanel controlPanel;
    private JSpinner overlaySpinnerX;
    private JSpinner overlaySpinnerY;
    private JLabel ySpinnerLabel;
    private JSpinner overlaySpinnerHeight;
    private JButton openOverlayImageButton;
    private JTextField insetTextField;
    private JSpinner textSpinnerX;
    private JSpinner textSpinnerY;
    private JSpinner cropSpinnerX;
    private JSpinner cropSpinnerY;
    private JSpinner cropSpinnerWidth;
    private JSpinner cropSpinnerHeight;
    private JSpinner overlaySpinnerWidth;
    private JButton openInputImageButton;
    private JCheckBox checkBox1;
    private JCheckBox checkBox2;
    private JCheckBox checkBox3;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        controlPanel = new JPanel();
        controlPanel.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:d:grow,left:10dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:d:grow,fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,center:8dlu:noGrow,center:8dlu:noGrow,top:14dlu:noGrow,center:27px:noGrow,center:8dlu:noGrow,top:4dlu:noGrow,center:8dlu:noGrow,top:5dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:6dlu:noGrow,center:6dlu:noGrow,top:14dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:8dlu:noGrow,center:8dlu:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,center:max(d;4px):noGrow,center:6dlu:noGrow,center:max(d;4px):noGrow"));
        final JLabel label1 = new JLabel();
        label1.setText("X:");
        CellConstraints cc = new CellConstraints();
        controlPanel.add(label1, new CellConstraints(3, 12, 1, 1, CellConstraints.RIGHT, CellConstraints.DEFAULT, new Insets(0, 5, 0, 0)));
        overlaySpinnerX = new JSpinner();
        controlPanel.add(overlaySpinnerX, cc.xy(5, 12, CellConstraints.FILL, CellConstraints.DEFAULT));
        overlaySpinnerY = new JSpinner();
        controlPanel.add(overlaySpinnerY, cc.xyw(9, 12, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        ySpinnerLabel = new JLabel();
        ySpinnerLabel.setText("Y:");
        controlPanel.add(ySpinnerLabel, cc.xy(7, 12, CellConstraints.RIGHT, CellConstraints.DEFAULT));
        final JLabel label2 = new JLabel();
        label2.setText("Width:");
        controlPanel.add(label2, new CellConstraints(3, 14, 1, 1, CellConstraints.RIGHT, CellConstraints.DEFAULT, new Insets(0, 5, 0, 0)));
        final JLabel label3 = new JLabel();
        label3.setText("Height:");
        controlPanel.add(label3, cc.xy(7, 14, CellConstraints.RIGHT, CellConstraints.DEFAULT));
        overlaySpinnerHeight = new JSpinner();
        controlPanel.add(overlaySpinnerHeight, cc.xyw(9, 14, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JSeparator separator1 = new JSeparator();
        separator1.setForeground(new Color(-7566196));
        controlPanel.add(separator1, cc.xyw(3, 16, 8, CellConstraints.FILL, CellConstraints.TOP));
        final JLabel label4 = new JLabel();
        label4.setText("Rectangle bounds");
        controlPanel.add(label4, new CellConstraints(3, 10, 10, 1, CellConstraints.LEFT, CellConstraints.DEFAULT, new Insets(0, 5, 0, 0)));
        openOverlayImageButton = new JButton();
        openOverlayImageButton.setText("Open overlay image...");
        controlPanel.add(openOverlayImageButton, cc.xyw(3, 7, 8));
        insetTextField = new JTextField();
        controlPanel.add(insetTextField, cc.xyw(3, 18, 8, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label5 = new JLabel();
        label5.setText("X:");
        controlPanel.add(label5, cc.xy(3, 20, CellConstraints.RIGHT, CellConstraints.DEFAULT));
        final JLabel label6 = new JLabel();
        label6.setText("Y:");
        controlPanel.add(label6, cc.xy(7, 20, CellConstraints.RIGHT, CellConstraints.DEFAULT));
        textSpinnerX = new JSpinner();
        controlPanel.add(textSpinnerX, cc.xy(5, 20, CellConstraints.FILL, CellConstraints.DEFAULT));
        textSpinnerY = new JSpinner();
        controlPanel.add(textSpinnerY, cc.xyw(9, 20, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JSeparator separator2 = new JSeparator();
        separator2.setForeground(new Color(-7566196));
        controlPanel.add(separator2, cc.xyw(3, 22, 8, CellConstraints.FILL, CellConstraints.FILL));
        final JLabel label7 = new JLabel();
        label7.setText("X:");
        controlPanel.add(label7, cc.xy(3, 27, CellConstraints.RIGHT, CellConstraints.DEFAULT));
        final JLabel label8 = new JLabel();
        label8.setText("Y:");
        controlPanel.add(label8, cc.xy(7, 27, CellConstraints.RIGHT, CellConstraints.DEFAULT));
        cropSpinnerX = new JSpinner();
        controlPanel.add(cropSpinnerX, cc.xy(5, 27, CellConstraints.FILL, CellConstraints.DEFAULT));
        cropSpinnerY = new JSpinner();
        controlPanel.add(cropSpinnerY, cc.xyw(9, 27, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label9 = new JLabel();
        label9.setText("Width:");
        controlPanel.add(label9, cc.xy(3, 29, CellConstraints.RIGHT, CellConstraints.DEFAULT));
        final JLabel label10 = new JLabel();
        label10.setText("Height:");
        controlPanel.add(label10, cc.xy(7, 29));
        cropSpinnerWidth = new JSpinner();
        controlPanel.add(cropSpinnerWidth, cc.xy(5, 29, CellConstraints.FILL, CellConstraints.DEFAULT));
        cropSpinnerHeight = new JSpinner();
        controlPanel.add(cropSpinnerHeight, cc.xyw(9, 29, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        overlaySpinnerWidth = new JSpinner();
        controlPanel.add(overlaySpinnerWidth, cc.xy(5, 14, CellConstraints.FILL, CellConstraints.DEFAULT));
        openInputImageButton = new JButton();
        openInputImageButton.setText("Open input image...");
        controlPanel.add(openInputImageButton, cc.xyw(3, 3, 8));
        final JSeparator separator3 = new JSeparator();
        separator3.setForeground(new Color(-7566196));
        controlPanel.add(separator3, cc.xyw(3, 5, 8, CellConstraints.FILL, CellConstraints.FILL));
        checkBox2 = new JCheckBox();
        checkBox2.setText("");
        controlPanel.add(checkBox2, cc.xyw(9, 17, 2, CellConstraints.RIGHT, CellConstraints.CENTER));
        checkBox1 = new JCheckBox();
        checkBox1.setText("");
        controlPanel.add(checkBox1, cc.xyw(9, 6, 2, CellConstraints.RIGHT, CellConstraints.CENTER));
        final JLabel label11 = new JLabel();
        label11.setText("Overlay image");
        controlPanel.add(label11, cc.xy(3, 6, CellConstraints.LEFT, CellConstraints.FILL));
        final JLabel label12 = new JLabel();
        label12.setText("Text inset");
        controlPanel.add(label12, cc.xy(3, 17, CellConstraints.LEFT, CellConstraints.CENTER));
        checkBox3 = new JCheckBox();
        checkBox3.setText("");
        controlPanel.add(checkBox3, cc.xy(10, 24, CellConstraints.RIGHT, CellConstraints.DEFAULT));
        final JLabel label13 = new JLabel();
        label13.setText("Crop rectangle");
        controlPanel.add(label13, cc.xy(3, 24, CellConstraints.LEFT, CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return controlPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
