package gui_designer_sandbox;

import com.intellij.uiDesigner.core.Spacer;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;

public class LayoutTestPanel {

    public JPanel mainPanel;
    private JButton openFileButton;
    private JSpinner overlaySpinnerX;
    private JSpinner overlaySpinnerY;
    private JButton applyButton;
    private JSpinner scaleWidthSpinner;
    private JSpinner scaleHeightSpinner;
    private JButton exitButton;
    private JTextField watermarkTextField;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("fill:d:grow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        final Spacer spacer1 = new Spacer();
        CellConstraints cc = new CellConstraints();
        mainPanel.add(spacer1, cc.xy(1, 1, CellConstraints.DEFAULT, CellConstraints.FILL));
        openFileButton = new JButton();
        openFileButton.setText("Open file...");
        mainPanel.add(openFileButton, cc.xy(1, 3));
        final JLabel label1 = new JLabel();
        label1.setText("Overlay upper-left (X,Y)");
        mainPanel.add(label1, cc.xy(1, 5));
        overlaySpinnerX = new JSpinner();
        mainPanel.add(overlaySpinnerX, cc.xy(1, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        overlaySpinnerY = new JSpinner();
        mainPanel.add(overlaySpinnerY, cc.xy(1, 9, CellConstraints.FILL, CellConstraints.DEFAULT));
        applyButton = new JButton();
        applyButton.setText("Apply");
        mainPanel.add(applyButton, cc.xy(1, 21));
        final JLabel label2 = new JLabel();
        label2.setText("Scale to (width, height)");
        mainPanel.add(label2, cc.xy(1, 11));
        scaleWidthSpinner = new JSpinner();
        mainPanel.add(scaleWidthSpinner, cc.xy(1, 13, CellConstraints.FILL, CellConstraints.DEFAULT));
        scaleHeightSpinner = new JSpinner();
        mainPanel.add(scaleHeightSpinner, cc.xy(1, 15, CellConstraints.FILL, CellConstraints.DEFAULT));
        exitButton = new JButton();
        exitButton.setText("Exit");
        mainPanel.add(exitButton, cc.xy(1, 23));
        final JLabel label3 = new JLabel();
        label3.setText("Watermark text");
        mainPanel.add(label3, cc.xy(1, 17));
        watermarkTextField = new JTextField();
        mainPanel.add(watermarkTextField, cc.xy(1, 19, CellConstraints.FILL, CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
